type(they,).
type(poor,).
type(cow,).
type(mot,).
type(told,).
type(jack,human).
type(man,human).
type(beans,).
type(mother,human).
type(angry,).
type(morning,).
type(out,).
type(beanstalk,).
type(castle,).
type(voice,).
type(giant,human).
type(down,).
type(harp,).
type(hen,).
type(egg,).
type(asleep,).
type(up,).
type(axe,).
type(nobody,).
type(eggs,).